version: '3.7'

services:
    web_back:
        build: ./backend
        command: python manage.py runserver 0.0.0.0:8000
        container_name: web-back
        volumes:
            - ./backend/:/usr/src/backend/
        ports:
            - 8000:8000
        env_file:
            - ./.env.backend.dev
        depends_on:
            - db
        networks:
            - net-habitissimo
    web_front:
        build: ./frontend
        command: python manage.py runserver 0.0.0.0:8001
        container_name: web-front
        volumes:
            - ./frontend/:/usr/src/frontend/
        ports:
            - 8001:8001
        env_file:
            - ./.env.frontend.dev
        depends_on:
            - db
        networks:
            - net-habitissimo
    db:
        image: postgres:12.0-alpine
        volumes:
            - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_MULTIPLE_DATABASES=habitissimo_back_dev,habitissimo_front_dev
            - POSTGRES_USER=user1
            - POSTGRES_PASSWORD=testuser123
        networks:
            - net-habitissimo

networks:
    net-habitissimo:
        driver: bridge
        ipam:
            driver: default