# Generated by Django 3.1.1 on 2020-09-16 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backpack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('max_number_of_items', models.IntegerField(blank=True, default=0, null=True, verbose_name='Máximo número de items')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Mochila',
                'verbose_name_plural': 'Mochilas',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='ItemsBackpack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('backpack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_in_backpack', to='api_rest_app.backpack', verbose_name='Mochila')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_in_backpack', to='api_rest_app.item', verbose_name='Histórico')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='backpacks',
            field=models.ManyToManyField(related_name='backpack_items', through='api_rest_app.ItemsBackpack', to='api_rest_app.Backpack', verbose_name='Mochila'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_items', to='api_rest_app.category', verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('backpack_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_rest_app.backpack')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='Orden')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_bags', to='api_rest_app.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Bolsa',
                'verbose_name_plural': 'Bolsas',
            },
            bases=('api_rest_app.backpack',),
        ),
    ]
