# Generated by Django 3.1.1 on 2020-09-16 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_app', '0002_auto_20200916_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsbackpack',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_in_backpack', to='api_rest_app.item', verbose_name='Item'),
        ),
    ]
